'use client'
import Header from '@/components/Header'
import { AuthProvider } from '@/context/AuthContext'
import 'leaflet/dist/leaflet.css'
import { Geist, Geist_Mono } from 'next/font/google'
import { usePathname } from 'next/navigation'
import { QueryClient, QueryClientProvider } from 'react-query'
import './globals.css'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

// export const metadata: Metadata = {
// 	title: 'Create Next App',
// 	description: 'Generated by create next app',
// }
const queryClient = new QueryClient()

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	const pathname = usePathname()
	const isAuthPage =
		pathname === '/login' ||
		pathname === '/register' ||
		pathname === '/dashboard'
	return (
		<html lang='en'>
			<body
				className={`${geistSans.variable} ${geistMono.variable} antialiased`}
			>
				<AuthProvider>
					<QueryClientProvider client={queryClient}>
						{!isAuthPage && <Header />}
						<main>{children}</main>
					</QueryClientProvider>
					{/* Uncomment the line below to include the Header component */}
				</AuthProvider>
			</body>
		</html>
	)
}
